const $=s=>document.querySelector(s);
const chooser=$("#areaChooser"),screen=$("#organizerScreen"),content=$("#organizerContent");
let snapshot=null,activeTab="overview";
const states={"DE-BW":"Baden-Württemberg","DE-BY":"Bayern","DE-BE":"Berlin","DE-BB":"Brandenburg","DE-HB":"Bremen","DE-HH":"Hamburg","DE-HE":"Hessen","DE-MV":"Mecklenburg-Vorpommern","DE-NI":"Niedersachsen","DE-NW":"Nordrhein-Westfalen","DE-RP":"Rheinland-Pfalz","DE-SL":"Saarland","DE-SN":"Sachsen","DE-ST":"Sachsen-Anhalt","DE-SH":"Schleswig-Holstein","DE-TH":"Thüringen"};
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const fmt=d=>d?new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(d)):"—";
const subject=id=>snapshot?.subjects?.find(x=>x.id===id);
const teacher=id=>snapshot?.teachers?.find(x=>x.id===id);
const options=(rows,label="name")=>(rows||[]).map(x=>`<option value="${x.id}">${esc(x[label])}</option>`).join("");
function toast(text){const el=document.createElement("div");el.className="organizer-toast";el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),2600)}
function openChooser(){document.body.classList.remove("school-mode");screen.hidden=true;chooser.hidden=false}
function openHome(){chooser.hidden=true;screen.hidden=true;document.body.classList.remove("school-mode");let button=document.querySelector("main.app>nav button[data-nav-target='homeSection']");button?.click();window.scrollTo(0,0)}
async function openSchool(){chooser.hidden=true;screen.hidden=false;document.body.classList.add("school-mode");window.scrollTo(0,0);await load()}
chooser?.addEventListener("click",e=>{const area=e.target.closest("[data-area]")?.dataset.area;if(area==="school")openSchool();if(area==="home")openHome()});
$("#organizerBack")?.addEventListener("click",openChooser);$("#organizerRefresh")?.addEventListener("click",load);
document.querySelector(".organizer-tabs")?.addEventListener("click",e=>{const b=e.target.closest("[data-tab]");if(!b)return;activeTab=b.dataset.tab;document.querySelectorAll(".organizer-tabs button").forEach(x=>x.classList.toggle("active",x===b));render()});
window.addEventListener("buhrsi:child-change",()=>setTimeout(openChooser,0));
setTimeout(()=>{if(window.BuhrsiOrganizerAPI?.child())openChooser()},700);

async function load(){content.innerHTML='<p class="organizer-loading">Organizer wird geladen …</p>';try{snapshot=await window.BuhrsiOrganizerAPI.snapshot();render();loadHoliday()}catch(e){content.innerHTML=`<p class="organizer-empty">Der Organizer ist noch nicht eingerichtet.<br><small>${esc(e.message)}</small></p>`}}
function render(){if(!snapshot)return;$("#schoolTitle").textContent=snapshot.profile?.school_name||"Schule";({overview:renderOverview,timetable:renderTimetable,grades:renderGrades,manage:renderManage}[activeTab]||renderOverview)();bindForms()}
function nextEvents(){const now=Date.now();return (snapshot.events||[]).filter(e=>!e.completed&&new Date(e.due_at).getTime()>=now).slice(0,5)}
function renderOverview(){
 const tasks=(snapshot.tasks||[]).filter(x=>!x.completed_at),events=nextEvents(),today=new Date().getDay()||7;
 const todayPlan=(snapshot.timetable||[]).filter(x=>x.weekday===today);
 content.innerHTML=`<div class="organizer-grid">
 <section class="organizer-panel"><h2>📅 Heute</h2><div class="organizer-list">${todayPlan.length?todayPlan.map(slot=>item(`<b>${esc(subject(slot.subject_id)?.name||"Fach")}</b><small>${slot.period}. Stunde · ${esc(slot.room||"Raum offen")} · ${esc(teacher(slot.teacher_id)?.name||"")}</small>`)).join(""):'<p class="organizer-empty">Heute ist kein Unterricht eingetragen.</p>'}</div></section>
 <section class="organizer-panel"><h2>📝 Nächste Termine</h2><div class="organizer-list">${events.length?events.map(e=>item(`<b>${esc(e.title)}</b><small>${esc(e.event_type)} · ${fmt(e.due_at)} · ${esc(subject(e.subject_id)?.name||"")}</small>`)).join(""):'<p class="organizer-empty">Keine offenen Termine.</p>'}</div></section>
 <section class="organizer-panel"><h2>⭐ Lernen & XP</h2><form id="learnForm" class="organizer-form"><label>Fach<select name="subject"><option value="">Allgemein</option>${options(snapshot.subjects)}</select></label><label>Minuten<input name="minutes" type="number" min="5" max="120" value="15" required></label><button>LERNZEIT ABSCHLIESSEN</button></form><p class="parent-only-note">Je 15 Minuten gibt es 5 XP, maximal 40 XP pro Lernzeit.</p></section>
 <section class="organizer-panel"><h2>🏠 Aufgaben daheim</h2><div class="organizer-list">${tasks.length?tasks.map(t=>`<div class="organizer-item"><div><b>${esc(t.title)}</b><small>${esc(t.details||"")}${t.due_at?` · bis ${fmt(t.due_at)}`:""}</small></div><button data-complete-task="${t.id}">+${t.xp_reward} XP</button></div>`).join(""):'<p class="organizer-empty">Alles erledigt!</p>'}</div></section>
 <section class="organizer-panel full"><h2>👩‍🏫 Fächer & Lehrer</h2><div class="organizer-list">${(snapshot.subjects||[]).map(s=>item(`<b><i class="subject-dot" style="background:${esc(s.color)}"></i>${esc(s.name)}</b><small>${s.is_major?"Hauptfach":"Nebenfach"}${teacherForSubject(s.id)}</small>`)).join("")||'<p class="organizer-empty">Noch keine Fächer angelegt.</p>'}</div></section></div>`;
}
function item(html,right=""){return `<div class="organizer-item"><div>${html}</div>${right}</div>`}
function teacherForSubject(id){const names=(snapshot.teachers||[]).filter(t=>t.subject_id===id).map(t=>t.name);return names.length?` · ${esc(names.join(", "))}`:""}
function renderTimetable(){const days=[[1,"Montag"],[2,"Dienstag"],[3,"Mittwoch"],[4,"Donnerstag"],[5,"Freitag"]],periods=[...new Set((snapshot.timetable||[]).map(x=>x.period))].sort((a,b)=>a-b);content.innerHTML=`<section class="organizer-panel timetable"><h2>🕘 Wochenplan</h2>${periods.length?`<table><thead><tr><th>Std.</th>${days.map(d=>`<th>${d[1]}</th>`).join("")}</tr></thead><tbody>${periods.map(p=>`<tr><th>${p}</th>${days.map(([d])=>{const x=snapshot.timetable.find(t=>t.weekday===d&&t.period===p);return x?`<td><b>${esc(subject(x.subject_id)?.name||"Fach")}</b><small>${esc(x.room||"")}</small><small>${esc(teacher(x.teacher_id)?.name||"")}</small></td>`:"<td>—</td>"}).join("")}</tr>`).join("")}</tbody></table>`:'<p class="organizer-empty">Noch kein Stundenplan angelegt.</p>'}</section>${snapshot.is_parent?timetableForm():''}`}
function weightedAverage(rows){const total=rows.reduce((n,g)=>n+Number(g.grade)*Number(g.weight),0),weights=rows.reduce((n,g)=>n+Number(g.weight),0);return weights?(total/weights).toFixed(2):"—"}
function renderGrades(){const majorIds=new Set((snapshot.subjects||[]).filter(s=>s.is_major).map(s=>s.id)),major=(snapshot.grades||[]).filter(g=>majorIds.has(g.subject_id)),minor=(snapshot.grades||[]).filter(g=>!majorIds.has(g.subject_id));content.innerHTML=`<div class="organizer-grid"><section class="organizer-panel full"><h2>📊 Notendurchschnitt</h2><div class="average-card"><div><b>${weightedAverage(snapshot.grades||[])}</b><small>Gesamt</small></div><div><b>${weightedAverage(major)}</b><small>Hauptfächer</small></div><div><b>${weightedAverage(minor)}</b><small>Nebenfächer</small></div></div></section><section class="organizer-panel"><h2>Noten</h2><div class="organizer-list">${(snapshot.grades||[]).map(g=>item(`<b>${esc(subject(g.subject_id)?.name||"Fach")} · Note ${Number(g.grade).toLocaleString("de-DE")}</b><small>${esc(g.category)} · ${fmt(g.graded_on)} · Gewicht ${g.weight}</small>`,`<em>+${g.xp_awarded} XP</em>`)).join("")||'<p class="organizer-empty">Noch keine Noten eingetragen.</p>'}</div></section>${snapshot.is_parent?gradeForm():parentHint()}</div>`}
function parentHint(){return '<section class="organizer-panel"><h2>Geschützt</h2><p class="parent-only-note">Noten und Schulangaben können nur im Elternzugang verändert werden.</p></section>'}
function renderManage(){if(!snapshot.is_parent){content.innerHTML=parentHint();return}content.innerHTML=`<div class="organizer-grid">${profileForm()}${subjectForm()}${teacherForm()}${eventForm()}${taskForm()}</div>`}
function profileForm(){const p=snapshot.profile||{};return `<section class="organizer-panel full"><h2>🏫 Schulprofil</h2><form id="profileForm" class="organizer-form"><label>Schule<input name="school_name" value="${esc(p.school_name)}" required></label><label>Schulart<input name="school_type" value="${esc(p.school_type)}" placeholder="z. B. Grundschule"></label><label>Klasse<input name="class_name" value="${esc(p.class_name)}" placeholder="z. B. 4a"></label><label>Klassenstufe<input name="grade_level" type="number" min="1" max="13" value="${esc(p.grade_level)}"></label><label>Bundesland<select name="federal_state">${Object.entries(states).map(([v,n])=>`<option value="${v}" ${p.federal_state===v?"selected":""}>${n}</option>`).join("")}</select></label><label>Schuljahr<input name="school_year" value="${esc(p.school_year)}" placeholder="2026/27"></label><button>SCHULPROFIL SPEICHERN</button></form></section>`}
function subjectForm(){return `<section class="organizer-panel"><h2>📚 Fach anlegen</h2><form id="subjectForm" class="organizer-form"><label class="wide">Name<input name="name" required></label><label>Art<select name="is_major"><option value="true">Hauptfach</option><option value="false">Nebenfach</option></select></label><label>Farbe<input name="color" type="color" value="#ffc55b"></label><button>FACH SPEICHERN</button></form></section>`}
function teacherForm(){return `<section class="organizer-panel"><h2>👩‍🏫 Lehrer anlegen</h2><form id="teacherForm" class="organizer-form"><label>Name<input name="name" required></label><label>Rolle<input name="role" value="Fachlehrer"></label><label>Fach<select name="subject_id"><option value="">Ohne Fach</option>${options(snapshot.subjects)}</select></label><label>E-Mail<input name="email" type="email"></label><label>Telefon<input name="phone"></label><label>Sprechzeit<input name="office_hours"></label><label class="wide">Hinweise<textarea name="notes"></textarea></label><button>LEHRER SPEICHERN</button></form></section>`}
function eventForm(){return `<section class="organizer-panel"><h2>📝 Schultermin</h2><form id="eventForm" class="organizer-form"><label>Titel<input name="title" required></label><label>Art<select name="event_type">${['Schulaufgabe','Test','Referat','Abgabe','Elternabend','Schultermin'].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Fach<select name="subject_id"><option value="">Allgemein</option>${options(snapshot.subjects)}</select></label><label>Datum<input name="due_at" type="datetime-local" required></label><label class="wide">Notiz<textarea name="notes"></textarea></label><button>TERMIN SPEICHERN</button></form></section>`}
function taskForm(){return `<section class="organizer-panel"><h2>🏠 Aufgabe daheim</h2><form id="taskForm" class="organizer-form"><label>Titel<input name="title" required></label><label>XP<input name="xp_reward" type="number" min="1" max="100" value="10"></label><label>Fällig<input name="due_at" type="datetime-local"></label><label>Details<input name="details"></label><button>AUFGABE ERSTELLEN</button></form></section>`}
function gradeForm(){return `<section class="organizer-panel"><h2>➕ Note eintragen</h2><form id="gradeForm" class="organizer-form"><label>Fach<select name="subject" required>${options(snapshot.subjects)}</select></label><label>Note<input name="grade" type="number" min="1" max="6" step="0.01" required></label><label>Art<select name="category">${['Schulaufgabe','Test','Mündlich','Referat','Sonstiges'].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Gewichtung<input name="weight" type="number" min="0.25" max="10" step="0.25" value="1"></label><label>Titel<input name="title"></label><label>Datum<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><button>NOTE & XP SPEICHERN</button></form></section>`}
function timetableForm(){return `<section class="organizer-panel"><h2>➕ Stunde eintragen</h2><form id="timetableForm" class="organizer-form"><label>Wochentag<select name="weekday">${['Montag','Dienstag','Mittwoch','Donnerstag','Freitag'].map((x,i)=>`<option value="${i+1}">${x}</option>`).join("")}</select></label><label>Stunde<input name="period" type="number" min="1" max="12" required></label><label>Fach<select name="subject_id" required>${options(snapshot.subjects)}</select></label><label>Lehrer<select name="teacher_id"><option value="">Offen</option>${options(snapshot.teachers)}</select></label><label>Beginn<input name="starts_at" type="time"></label><label>Ende<input name="ends_at" type="time"></label><label>Raum<input name="room"></label><button>STUNDE SPEICHERN</button></form></section>`}
function bindForms(){
 const bind=(id,table,transform=x=>x,upsert=false)=>{$("#"+id)?.addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{let v=transform(Object.fromEntries(new FormData(e.currentTarget)));await window.BuhrsiOrganizerAPI.save(table,v,upsert);toast("Gespeichert ✓");await load()}catch(err){toast(err.message)}finally{b.disabled=false}})};
 bind("profileForm","school_profiles",v=>({...v,grade_level:v.grade_level?Number(v.grade_level):null,updated_at:new Date().toISOString()}),true);
 bind("subjectForm","school_subjects",v=>({...v,is_major:v.is_major==="true"}));bind("teacherForm","school_teachers",cleanEmpty);bind("eventForm","school_events",v=>cleanEmpty({...v,due_at:new Date(v.due_at).toISOString()}));bind("taskForm","home_tasks",v=>cleanEmpty({...v,xp_reward:Number(v.xp_reward),due_at:v.due_at?new Date(v.due_at).toISOString():null}));bind("timetableForm","school_timetable",v=>cleanEmpty({...v,weekday:Number(v.weekday),period:Number(v.period)}),true);
 $("#learnForm")?.addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const v=Object.fromEntries(new FormData(e.currentTarget)),r=await window.BuhrsiOrganizerAPI.learn(Number(v.minutes),v.subject);toast(`Stark! +${r.xp_awarded} XP`);await load()}catch(err){toast(err.message)}finally{b.disabled=false}});
 $("#gradeForm")?.addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const v=Object.fromEntries(new FormData(e.currentTarget)),r=await window.BuhrsiOrganizerAPI.addGrade({...v,grade:Number(v.grade),weight:Number(v.weight)});toast(`Note gespeichert · +${r.xp_awarded} XP`);await load()}catch(err){toast(err.message)}finally{b.disabled=false}});
 content.querySelectorAll("[data-complete-task]").forEach(b=>b.addEventListener("click",async()=>{b.disabled=true;try{const r=await window.BuhrsiOrganizerAPI.completeTask(b.dataset.completeTask);toast(`Erledigt! +${r.xp_awarded} XP`);await load()}catch(err){toast(err.message);b.disabled=false}}));
}
function cleanEmpty(v){return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,x===""?null:x]))}
async function loadHoliday(){const card=$("#holidayCard"),code=snapshot?.profile?.federal_state;if(!code){card.querySelector("b").textContent="Bundesland im Schulprofil auswählen";return}const now=new Date(),to=new Date(now);to.setFullYear(to.getFullYear()+1);const iso=d=>d.toISOString().slice(0,10);try{const url=`https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE&subdivisionCode=${code}&validFrom=${iso(now)}&validTo=${iso(to)}&languageIsoCode=DE`;const rows=await fetch(url).then(r=>{if(!r.ok)throw new Error();return r.json()});const next=rows.filter(x=>new Date(x.endDate)>=now).sort((a,b)=>new Date(a.startDate)-new Date(b.startDate))[0];if(!next)throw new Error();const name=next.name?.find(x=>x.language==="DE")?.text||next.name?.[0]?.text||"Ferien";const days=Math.max(0,Math.ceil((new Date(next.startDate)-now)/86400000));card.querySelector("b").textContent=`${name} · ${days===0?"jetzt":`in ${days} Tagen`}`;card.querySelector("p").textContent=`${fmt(next.startDate)} bis ${fmt(next.endDate)} · ${states[code]}`;}catch(e){card.querySelector("b").textContent=`Ferien für ${states[code]||code}`;card.querySelector("p").textContent="Ferientermine konnten gerade nicht geladen werden."}}
