const $=s=>document.querySelector(s);
const chooser=$("#areaChooser"),screen=$("#organizerScreen"),content=$("#organizerContent");
let snapshot=null,activeTab="overview",learningTimerInterval=null;
const states={"DE-BW":"Baden-Württemberg","DE-BY":"Bayern","DE-BE":"Berlin","DE-BB":"Brandenburg","DE-HB":"Bremen","DE-HH":"Hamburg","DE-HE":"Hessen","DE-MV":"Mecklenburg-Vorpommern","DE-NI":"Niedersachsen","DE-NW":"Nordrhein-Westfalen","DE-RP":"Rheinland-Pfalz","DE-SL":"Saarland","DE-SN":"Sachsen","DE-ST":"Sachsen-Anhalt","DE-SH":"Schleswig-Holstein","DE-TH":"Thüringen"};
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const fmt=d=>d?new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(d)):"—";
const hhmm=t=>t?String(t).slice(0,5):"—";
const subject=id=>snapshot?.subjects?.find(x=>x.id===id);
const teacher=id=>snapshot?.teachers?.find(x=>x.id===id);
const options=(rows,label="name",selected="")=>(rows||[]).map(x=>`<option value="${x.id}" ${String(x.id)===String(selected)?"selected":""}>${esc(x[label])}</option>`).join("");
function toast(text){const el=document.createElement("div");el.className="organizer-toast";el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),2600)}
function openChooser(){document.body.classList.remove("school-mode");screen.hidden=true;chooser.hidden=false}
function openHome(){chooser.hidden=true;screen.hidden=true;document.body.classList.remove("school-mode");let button=document.querySelector("main.app>nav button[data-nav-target='homeSection']");button?.click();window.scrollTo(0,0)}
async function openSchool(){chooser.hidden=true;screen.hidden=false;document.body.classList.add("school-mode");window.scrollTo(0,0);await load()}
function setTab(tab){activeTab=tab;document.querySelectorAll(".organizer-tabs button").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab))}
chooser?.addEventListener("click",e=>{const area=e.target.closest("[data-area]")?.dataset.area;if(area==="school")openSchool();if(area==="home")openHome()});
$("#organizerBack")?.addEventListener("click",openChooser);$("#organizerRefresh")?.addEventListener("click",load);$("#areaLogout")?.addEventListener("click",()=>window.BuhrsiAuth?.logout?.());
document.querySelector(".organizer-tabs")?.addEventListener("click",e=>{const b=e.target.closest("[data-tab]");if(!b)return;activeTab=b.dataset.tab;document.querySelectorAll(".organizer-tabs button").forEach(x=>x.classList.toggle("active",x===b));render()});
window.addEventListener("buhrsi:child-change",()=>setTimeout(openChooser,0));
setTimeout(()=>{if(window.BuhrsiOrganizerAPI?.child())openChooser()},700);

async function load(){content.innerHTML='<p class="organizer-loading">Organizer wird geladen …</p>';try{snapshot=await window.BuhrsiOrganizerAPI.snapshot();render();loadHoliday()}catch(e){content.innerHTML=`<p class="organizer-empty">Der Organizer ist noch nicht eingerichtet.<br><small>${esc(e.message)}</small></p>`}}
function render(){if(!snapshot)return;const profile=snapshot.profile||{},mode=$("#organizerScreen .eyebrow"),contact=$("#schoolContact");$("#schoolTitle").textContent=profile.school_name||"Schule einrichten";if(contact){const details=[];if(profile.school_phone)details.push(`<a href="tel:${esc(String(profile.school_phone).replace(/[^+\d]/g,""))}">☎ ${esc(profile.school_phone)}</a>`);if(profile.school_city)details.push(`<span>📍 ${esc(profile.school_city)}</span>`);contact.innerHTML=details.join("");contact.hidden=!details.length}if(mode)mode.textContent=snapshot.is_parent?"ELTERNMODUS · BEARBEITEN":"KINDERMODUS · ANSEHEN";({overview:renderOverview,timetable:renderTimetable,grades:renderGrades,manage:renderManage}[activeTab]||renderOverview)();bindForms()}
function nextEvents(){const now=Date.now();return (snapshot.events||[]).filter(e=>!e.completed&&new Date(e.due_at).getTime()>=now).slice(0,5)}
function renderOverview(){
 const tasks=(snapshot.tasks||[]).filter(x=>!x.completed_at),events=nextEvents(),today=new Date().getDay()||7;
 const todayPlan=(snapshot.timetable||[]).filter(x=>x.weekday===today),schedule=Object.fromEntries((snapshot.schedule||[]).filter(x=>x.entry_type==="lesson").map(x=>[x.period,x]));
 content.innerHTML=`<div class="organizer-grid">
 <section class="organizer-panel"><h2>📅 Heute</h2><div class="organizer-list">${todayPlan.length?todayPlan.map(slot=>{const s=subject(slot.subject_id),time=schedule[slot.period];return item(`<b><i class="subject-dot" style="background:${esc(s?.color||"#ffc55b")}"></i>${esc(s?.name||"Fach")}</b><small>${slot.period}. Stunde${time?` · ${hhmm(time.starts_at)}–${hhmm(time.ends_at)}`:""} · ${esc(slot.room||"Raum offen")} · ${esc(teacher(slot.teacher_id)?.name||"")}</small>`)}).join(""):'<p class="organizer-empty">Heute ist kein Unterricht eingetragen.</p>'}</div></section>
 <section class="organizer-panel"><h2>📝 Nächste Termine</h2><div class="organizer-list">${events.length?events.map(e=>item(`<b>${esc(e.title)}</b><small>${esc(e.event_type)} · ${fmt(e.due_at)} · ${esc(subject(e.subject_id)?.name||"")}</small>`)).join(""):'<p class="organizer-empty">Keine offenen Termine.</p>'}</div></section>
 <section class="organizer-panel learning-panel"><h2>⏱ Lernen & XP</h2><div class="learning-stopwatch"><label>Fach<select id="learningSubject"><option value="">Allgemein</option>${options(snapshot.subjects)}</select></label><div id="learningClock" class="learning-clock">00:00:00</div><p id="learningXpPreview" class="learning-xp-preview">Ab 5 Minuten wird die Lernzeit gespeichert.</p><div class="learning-controls"><button id="learningStart" type="button">LERNEN STARTEN</button><button id="learningStop" type="button" hidden>FERTIG · XP ERHALTEN</button><button id="learningCancel" class="form-cancel" type="button" hidden>ABBRECHEN</button></div></div><p class="parent-only-note">Die Stoppuhr läuft auch weiter, wenn du die Seite verlässt. Maximal 120 Minuten und 40 XP pro Lernzeit.</p></section>
 <section class="organizer-panel"><h2>🏠 Aufgaben daheim</h2><div class="organizer-list">${tasks.length?tasks.map(t=>`<div class="organizer-item"><div><b>${esc(t.title)}</b><small>${esc(t.details||"")}${t.due_at?` · bis ${fmt(t.due_at)}`:""}</small></div><button data-complete-task="${t.id}">+${t.xp_reward} XP</button></div>`).join(""):'<p class="organizer-empty">Alles erledigt!</p>'}</div></section>
 <section class="organizer-panel full"><h2>👩‍🏫 Fächer & Lehrer</h2><div class="organizer-list">${(snapshot.subjects||[]).map(s=>item(`<b><i class="subject-dot" style="background:${esc(s.color)}"></i>${esc(s.name)}</b><small>${s.is_major?"Hauptfach":"Nebenfach"}${teacherForSubject(s.id)}</small>`)).join("")||'<p class="organizer-empty">Noch keine Fächer angelegt.</p>'}</div></section>${snapshot.is_parent?learningHistoryPanel():""}</div>`;
}
function learningAward(minutes){return minutes<5?0:Math.min(40,Math.max(5,Math.floor(minutes/15)*5))}
function learningTimerKey(){return "buhrsis:learning-timer:"+(window.BuhrsiOrganizerAPI?.child()?.id||"unknown")}
function readLearningTimer(){try{const value=JSON.parse(localStorage.getItem(learningTimerKey())||"null");return value&&Number(value.startedAt)>0?value:null}catch(e){return null}}
function writeLearningTimer(value){try{value?localStorage.setItem(learningTimerKey(),JSON.stringify(value)):localStorage.removeItem(learningTimerKey())}catch(e){}}
function formatElapsed(seconds){const safe=Math.max(0,Math.min(7200,Math.floor(seconds))),h=Math.floor(safe/3600),m=Math.floor(safe%3600/60),s=safe%60;return [h,m,s].map(x=>String(x).padStart(2,"0")).join(":")}
function learningHistoryPanel(){const rows=(snapshot.learning||[]).slice(0,14);return `<section class="organizer-panel full learning-history"><h2>📖 Letzte Lernzeiten</h2><div class="organizer-list">${rows.length?rows.map(row=>{const end=new Date(row.completed_at),start=new Date(end.getTime()-Number(row.minutes||0)*60000),date=end.toLocaleDateString("de-DE",{weekday:"short",day:"2-digit",month:"2-digit"}),range=`${start.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}–${end.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}`;return item(`<b>${esc(subject(row.subject_id)?.name||"Allgemein")}</b><small>${esc(date)} · ${esc(range)} Uhr · ${Number(row.minutes)||0} Min.</small>`,`<em>+${Number(row.xp_awarded)||0} XP</em>`) }).join(""):'<p class="organizer-empty">Noch keine Lernzeit gespeichert.</p>'}</div></section>`}
function bindLearningTimer(){
 clearInterval(learningTimerInterval);learningTimerInterval=null;
 const subjectSelect=$("#learningSubject"),clock=$("#learningClock"),preview=$("#learningXpPreview"),startButton=$("#learningStart"),stopButton=$("#learningStop"),cancelButton=$("#learningCancel");
 if(!subjectSelect||!clock||!preview||!startButton||!stopButton||!cancelButton)return;
 let active=readLearningTimer(),saving=false;
 const paint=()=>{active=readLearningTimer();const elapsed=active?Math.min(7200,Math.max(0,Math.floor((Date.now()-Number(active.startedAt))/1000))):0,minutes=Math.floor(elapsed/60),award=learningAward(minutes);clock.textContent=formatElapsed(elapsed);subjectSelect.disabled=Boolean(active);startButton.hidden=Boolean(active);stopButton.hidden=!active;cancelButton.hidden=!active;if(active){subjectSelect.value=active.subjectId||"";preview.textContent=minutes<5?`Noch ${5-minutes} Min. bis zur Speicherung`:`${minutes} Min. gelernt · aktuell +${award} XP`;stopButton.disabled=saving}else preview.textContent="Ab 5 Minuten wird die Lernzeit gespeichert."};
 const finish=async()=>{if(!active||saving)return;const minutes=Math.min(120,Math.floor((Date.now()-Number(active.startedAt))/60000));if(minutes<5){toast("Mindestens 5 Minuten lernen – die Stoppuhr läuft weiter.");return}saving=true;paint();try{const r=await window.BuhrsiOrganizerAPI.learn(minutes,active.subjectId||null);writeLearningTimer(null);active=null;toast(`Lernzeit gespeichert · +${r.xp_awarded} XP`);await load()}catch(err){saving=false;paint();toast(err.message)}};
 startButton.addEventListener("click",()=>{active={startedAt:Date.now(),subjectId:subjectSelect.value||null};writeLearningTimer(active);paint();learningTimerInterval=setInterval(paint,1000)});
 stopButton.addEventListener("click",finish);
 cancelButton.addEventListener("click",()=>{if(!confirm("Lernzeit wirklich abbrechen? Sie wird nicht gespeichert."))return;writeLearningTimer(null);active=null;paint();clearInterval(learningTimerInterval);learningTimerInterval=null;toast("Lernzeit abgebrochen.")});
 paint();if(active)learningTimerInterval=setInterval(paint,1000);
}
function item(html,right=""){return `<div class="organizer-item"><div>${html}</div>${right}</div>`}
function teacherForSubject(id){const names=(snapshot.teachers||[]).filter(t=>t.subject_id===id).map(t=>t.name);return names.length?` · ${esc(names.join(", "))}`:""}
function lessonRow(p,days,time){return `<tr><th>${p}<small>${time?`${hhmm(time.starts_at)}<br>${hhmm(time.ends_at)}`:""}</small></th>${days.map(([d,day])=>{const x=(snapshot.timetable||[]).find(t=>t.weekday===d&&t.period===p),s=x&&subject(x.subject_id);if(snapshot.is_parent)return `<td class="lesson-cell timetable-edit-cell" style="--subject-color:${esc(s?.color||"#59635f")}"><select class="timetable-subject-select" data-timetable-subject data-weekday="${d}" data-period="${p}" aria-label="${esc(day)}, ${p}. Stunde"><option value="">— Frei —</option>${options(snapshot.subjects,"name",x?.subject_id||"")}</select><small>${x?esc([x.room,teacher(x.teacher_id)?.name].filter(Boolean).join(" · ")):"Fach auswählen"}</small></td>`;return x?`<td class="lesson-cell" style="--subject-color:${esc(s?.color||"#ffc55b")}"><b>${esc(s?.name||"Fach")}</b><small>${esc(x.room||"")}</small><small>${esc(teacher(x.teacher_id)?.name||"")}</small></td>`:"<td>—</td>"}).join("")}</tr>`}
function renderTimetable(){const days=[[1,"Montag"],[2,"Dienstag"],[3,"Mittwoch"],[4,"Donnerstag"],[5,"Freitag"]],entries=[...(snapshot.schedule||[])].sort((a,b)=>String(a.starts_at).localeCompare(String(b.starts_at))),used=new Set(entries.filter(x=>x.entry_type==="lesson").map(x=>x.period)),planned=[...new Set((snapshot.timetable||[]).map(x=>x.period))],fallback=snapshot.is_parent&&used.size===0&&planned.length===0?[1,2,3,4,5,6,7,8]:[],missing=[...new Set([...planned,...fallback])].filter(p=>!used.has(p)).sort((a,b)=>a-b),rows=[...entries.map(x=>x.entry_type==="break"?`<tr class="break-row"><th>☕</th><td colspan="5"><b>${esc(x.name)}</b> · ${hhmm(x.starts_at)}–${hhmm(x.ends_at)}</td></tr>`:lessonRow(x.period,days,x)),...missing.map(p=>lessonRow(p,days,null))].join("");content.innerHTML=`<section class="organizer-panel timetable"><h2>🕘 Wochenplan</h2>${snapshot.is_parent?'<p class="timetable-help">Fach direkt in der gewünschten Zelle auswählen. „Frei“ entfernt den Eintrag.</p>':""}${rows?`<table><thead><tr><th>Std.</th>${days.map(d=>`<th>${d[1]}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table>`:'<p class="organizer-empty">Noch kein Stundenplan angelegt.</p>'}</section>${snapshot.is_parent?`${scheduleForms()}${timetableForm()}`:""}`}
function weightedAverage(rows){const total=rows.reduce((n,g)=>n+Number(g.grade)*Number(g.weight),0),weights=rows.reduce((n,g)=>n+Number(g.weight),0);return weights?(total/weights).toFixed(2):"—"}
function renderGrades(){const majorIds=new Set((snapshot.subjects||[]).filter(s=>s.is_major).map(s=>s.id)),major=(snapshot.grades||[]).filter(g=>majorIds.has(g.subject_id)),minor=(snapshot.grades||[]).filter(g=>!majorIds.has(g.subject_id));content.innerHTML=`<div class="organizer-grid"><section class="organizer-panel full"><h2>📊 Notendurchschnitt</h2><div class="average-card"><div><b>${weightedAverage(snapshot.grades||[])}</b><small>Gesamt</small></div><div><b>${weightedAverage(major)}</b><small>Hauptfächer</small></div><div><b>${weightedAverage(minor)}</b><small>Nebenfächer</small></div></div></section><section class="organizer-panel"><h2>Noten</h2><div class="organizer-list">${(snapshot.grades||[]).map(g=>item(`<b>${esc(subject(g.subject_id)?.name||"Fach")} · Note ${Number(g.grade).toLocaleString("de-DE")}</b><small>${esc(g.category)} · ${fmt(g.graded_on)} · Gewicht ${g.weight}</small>`,`<em>+${g.xp_awarded} XP</em>`)).join("")||'<p class="organizer-empty">Noch keine Noten eingetragen.</p>'}</div></section>${snapshot.is_parent?gradeForm():parentHint()}</div>`}
function parentHint(){return '<section class="organizer-panel"><h2>Geschützt</h2><p class="parent-only-note">Du bist gerade als Kind angemeldet. Noten und Schulangaben können nur im Elternkonto verändert werden.</p><button id="parentLoginFromOrganizer" class="organizer-parent-login" type="button">ZUR ELTERN-ANMELDUNG</button></section>'}
function renderManage(){if(!snapshot.is_parent){content.innerHTML=parentHint();return}content.innerHTML=`<div class="organizer-grid">${profileForm()}${subjectForm()}${teacherForm()}${eventForm()}${taskForm()}</div>`}
function profileForm(){const p=snapshot.profile||{};return `<section class="organizer-panel full school-profile-panel"><h2>🏫 Eigene Schule für ${esc(window.BuhrsiOrganizerAPI.child()?.name||"dieses Kind")}</h2><form id="schoolSearchForm" class="organizer-form school-search"><label>Bundesland<select name="state">${Object.entries(states).map(([v,n])=>`<option value="${v}" ${p.federal_state===v?"selected":""}>${n}</option>`).join("")}</select></label><label class="wide">Schule suchen<input name="query" minlength="3" placeholder="Name der Schule" required></label><button>SCHULE SUCHEN</button></form><div id="schoolSearchResults" class="school-search-results"></div><p class="parent-only-note">Keine passende Schule dabei? Alle Angaben können darunter auch selbst eingetragen werden.</p><form id="profileForm" class="organizer-form"><input type="hidden" name="external_school_id" value="${esc(p.external_school_id)}"><input type="hidden" name="school_source" value="${esc(p.school_source||"manual")}"><label>Schule<input name="school_name" value="${esc(p.school_name)}" required></label><label>Schulart<input name="school_type" value="${esc(p.school_type)}" placeholder="z. B. Grundschule"></label><label>Adresse<input name="school_address" value="${esc(p.school_address)}"></label><label>PLZ<input name="school_zip" value="${esc(p.school_zip)}"></label><label>Ort<input name="school_city" value="${esc(p.school_city)}"></label><label>Telefon der Schule<input name="school_phone" type="tel" value="${esc(p.school_phone)}" placeholder="z. B. 0921 12345"></label><label>Klasse<input name="class_name" value="${esc(p.class_name)}" placeholder="z. B. 4a"></label><label>Klassenstufe<input name="grade_level" type="number" min="1" max="13" value="${esc(p.grade_level)}"></label><label>Bundesland<select name="federal_state">${Object.entries(states).map(([v,n])=>`<option value="${v}" ${p.federal_state===v?"selected":""}>${n}</option>`).join("")}</select></label><label>Schuljahr<input name="school_year" value="${esc(p.school_year)}" placeholder="2026/27"></label><button>SCHULPROFIL SPEICHERN</button></form></section>`}
function subjectForm(){return `<section class="organizer-panel"><h2>📚 Fächer & Farben</h2><div class="organizer-list subject-manage-list">${(snapshot.subjects||[]).map(s=>item(`<b><i class="subject-dot" style="background:${esc(s.color)}"></i>${esc(s.name)}</b><small>${s.is_major?"Hauptfach":"Nebenfach"}</small>`,`<button type="button" class="subject-edit-button" data-edit-subject="${s.id}">BEARBEITEN</button>`)).join("")||'<p class="organizer-empty">Noch keine Fächer angelegt.</p>'}</div><form id="subjectForm" class="organizer-form"><input type="hidden" name="id"><label class="wide">Name<input name="name" required></label><label>Art<select name="is_major"><option value="true">Hauptfach</option><option value="false">Nebenfach</option></select></label><label>Eigene Farbe<input name="color" type="color" value="#ffc55b"></label><button id="subjectSaveButton">FACH SPEICHERN</button><button id="subjectCancelButton" class="form-cancel" type="button" hidden>ABBRECHEN</button></form></section>`}
function teacherForm(){return `<section class="organizer-panel"><h2>👩‍🏫 Lehrer anlegen</h2><form id="teacherForm" class="organizer-form"><label>Name<input name="name" required></label><label>Rolle<input name="role" value="Fachlehrer"></label><label>Fach<select name="subject_id"><option value="">Ohne Fach</option>${options(snapshot.subjects)}</select></label><label>E-Mail<input name="email" type="email"></label><label>Telefon<input name="phone"></label><label>Sprechzeit<input name="office_hours"></label><label class="wide">Hinweise<textarea name="notes"></textarea></label><button>LEHRER SPEICHERN</button></form></section>`}
function eventForm(){return `<section class="organizer-panel"><h2>📝 Schultermin</h2><form id="eventForm" class="organizer-form"><label>Titel<input name="title" required></label><label>Art<select name="event_type">${['Schulaufgabe','Test','Referat','Abgabe','Elternabend','Schultermin'].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Fach<select name="subject_id"><option value="">Allgemein</option>${options(snapshot.subjects)}</select></label><label>Datum<input name="due_at" type="datetime-local" required></label><label class="wide">Notiz<textarea name="notes"></textarea></label><button>TERMIN SPEICHERN</button></form></section>`}
function taskForm(){return `<section class="organizer-panel"><h2>🏠 Aufgabe daheim</h2><form id="taskForm" class="organizer-form"><label>Titel<input name="title" required></label><label>XP<input name="xp_reward" type="number" min="1" max="100" value="10"></label><label>Fällig<input name="due_at" type="datetime-local"></label><label>Details<input name="details"></label><button>AUFGABE ERSTELLEN</button></form></section>`}
function gradeForm(){return `<section class="organizer-panel"><h2>➕ Note eintragen</h2><form id="gradeForm" class="organizer-form"><label>Fach<select name="subject" required>${options(snapshot.subjects)}</select></label><label>Note<input name="grade" type="number" min="1" max="6" step="0.01" required></label><label>Art<select name="category">${['Schulaufgabe','Test','Mündlich','Referat','Sonstiges'].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Gewichtung<input name="weight" type="number" min="0.25" max="10" step="0.25" value="1"></label><label>Titel<input name="title"></label><label>Datum<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><button>NOTE & XP SPEICHERN</button></form></section>`}
function scheduleForms(){const rows=(snapshot.schedule||[]).map(x=>`<div class="organizer-item"><div><b>${x.entry_type==="break"?"☕ "+esc(x.name):`${x.period}. ${esc(x.name)}`}</b><small>${hhmm(x.starts_at)}–${hhmm(x.ends_at)}</small></div><button type="button" class="danger-link" data-remove="school_schedule_entries" data-id="${x.id}">LÖSCHEN</button></div>`).join("");return `<section class="organizer-panel schedule-editor"><h2>⏱ Stundenzeiten & Pausen</h2><div class="organizer-list">${rows||'<p class="organizer-empty">Noch keine Zeiten festgelegt.</p>'}</div><form id="lessonTimeForm" class="organizer-form"><label>Stunde<input name="period" type="number" min="1" max="20" required></label><label>Bezeichnung<input name="name" value="Unterricht" required></label><label>Beginn<input name="starts_at" type="time" required></label><label>Ende<input name="ends_at" type="time" required></label><button>STUNDENZEIT SPEICHERN</button></form><form id="breakForm" class="organizer-form"><label>Pause<input name="name" value="Pause" required></label><label>Beginn<input name="starts_at" type="time" required></label><label>Ende<input name="ends_at" type="time" required></label><button>PAUSE SPEICHERN</button></form></section>`}
function timetableForm(){return `<section class="organizer-panel"><h2>➕ Fach in den Plan eintragen</h2><form id="timetableForm" class="organizer-form"><label>Wochentag<select name="weekday">${['Montag','Dienstag','Mittwoch','Donnerstag','Freitag'].map((x,i)=>`<option value="${i+1}">${x}</option>`).join("")}</select></label><label>Stunde<input name="period" type="number" min="1" max="12" required></label><label>Fach<select name="subject_id" required>${options(snapshot.subjects)}</select></label><label>Lehrer<select name="teacher_id"><option value="">Offen</option>${options(snapshot.teachers)}</select></label><label>Raum<input name="room"></label><button>STUNDE SPEICHERN</button></form></section>`}
function bindForms(){
 const bind=(id,table,transform=x=>x,upsert=false)=>{$("#"+id)?.addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{let v=transform(Object.fromEntries(new FormData(e.currentTarget)));await window.BuhrsiOrganizerAPI.save(table,v,upsert);toast("Gespeichert ✓");await load()}catch(err){toast(err.message)}finally{b.disabled=false}})};
 bind("profileForm","school_profiles",v=>({...v,grade_level:v.grade_level?Number(v.grade_level):null,updated_at:new Date().toISOString()}),true);
 bind("subjectForm","school_subjects",v=>{const row={...v,is_major:v.is_major==="true"};if(!row.id)delete row.id;return row},true);bind("teacherForm","school_teachers",cleanEmpty);bind("eventForm","school_events",v=>cleanEmpty({...v,due_at:new Date(v.due_at).toISOString()}));bind("taskForm","home_tasks",v=>cleanEmpty({...v,xp_reward:Number(v.xp_reward),due_at:v.due_at?new Date(v.due_at).toISOString():null}));bind("timetableForm","school_timetable",v=>cleanEmpty({...v,weekday:Number(v.weekday),period:Number(v.period)}),true);
 bind("lessonTimeForm","school_schedule_entries",v=>({...v,entry_type:"lesson",period:Number(v.period)}),true);bind("breakForm","school_schedule_entries",v=>({...v,entry_type:"break",period:null}));
 bindSchoolSearch();
 bindLearningTimer();
 $("#gradeForm")?.addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const v=Object.fromEntries(new FormData(e.currentTarget)),r=await window.BuhrsiOrganizerAPI.addGrade({...v,grade:Number(v.grade),weight:Number(v.weight)});toast(`Note gespeichert · +${r.xp_awarded} XP`);await load()}catch(err){toast(err.message)}finally{b.disabled=false}});
 content.querySelectorAll("[data-complete-task]").forEach(b=>b.addEventListener("click",async()=>{b.disabled=true;try{const r=await window.BuhrsiOrganizerAPI.completeTask(b.dataset.completeTask);toast(`Erledigt! +${r.xp_awarded} XP`);await load()}catch(err){toast(err.message);b.disabled=false}}));
 content.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",async()=>{if(!confirm("Eintrag wirklich löschen?"))return;b.disabled=true;try{await window.BuhrsiOrganizerAPI.remove(b.dataset.remove,b.dataset.id);toast("Gelöscht ✓");await load()}catch(err){toast(err.message);b.disabled=false}}));
 content.querySelectorAll("[data-edit-subject]").forEach(b=>b.addEventListener("click",()=>{const s=subject(b.dataset.editSubject),form=$("#subjectForm");if(!s||!form)return;form.elements.id.value=s.id;form.elements.name.value=s.name||"";form.elements.is_major.value=String(Boolean(s.is_major));form.elements.color.value=s.color||"#ffc55b";$("#subjectSaveButton").textContent="ÄNDERUNGEN SPEICHERN";$("#subjectCancelButton").hidden=false;form.scrollIntoView({behavior:"smooth",block:"center"});form.elements.name.focus()}));
 $("#subjectCancelButton")?.addEventListener("click",()=>{const form=$("#subjectForm");form.reset();form.elements.id.value="";$("#subjectSaveButton").textContent="FACH SPEICHERN";$("#subjectCancelButton").hidden=true});
 content.querySelectorAll("[data-timetable-subject]").forEach(select=>select.addEventListener("change",async()=>{const weekday=Number(select.dataset.weekday),period=Number(select.dataset.period),existing=(snapshot.timetable||[]).find(x=>x.weekday===weekday&&x.period===period),previous=existing?.subject_id||"";select.disabled=true;try{if(select.value){await window.BuhrsiOrganizerAPI.save("school_timetable",cleanEmpty({weekday,period,subject_id:select.value,teacher_id:existing?.teacher_id||null,room:existing?.room||null}),true);toast("Stundenplan gespeichert ✓")}else if(existing){await window.BuhrsiOrganizerAPI.remove("school_timetable",existing.id);toast("Stunde entfernt ✓")}await load()}catch(err){select.value=previous;select.disabled=false;toast(err.message)}}));
 $("#parentLoginFromOrganizer")?.addEventListener("click",()=>window.BuhrsiAuth?.logout?.());
}
function bindSchoolSearch(){const form=$("#schoolSearchForm"),results=$("#schoolSearchResults");if(!form||!results)return;form.addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter,v=Object.fromEntries(new FormData(form)),state=v.state.replace("DE-","");b.disabled=true;results.innerHTML='<p class="organizer-loading">Schulen werden gesucht …</p>';try{const url=`https://jedeschule.codefor.de/schools/?limit=12&state=${encodeURIComponent(state)}&name=${encodeURIComponent(v.query.trim())}`,rows=await fetch(url).then(r=>{if(!r.ok)throw new Error("Schulsuche nicht erreichbar");return r.json()});results.innerHTML=rows.length?rows.map((s,i)=>`<button type="button" class="school-result" data-school-result="${i}"><b>${esc(s.name)}</b><small>${esc([s.school_type,s.address,[s.zip,s.city].filter(Boolean).join(" "),s.phone].filter(Boolean).join(" · "))}</small></button>`).join(""):'<p class="organizer-empty">Keine Schule gefunden. Bitte den Namen kürzer suchen oder selbst eintragen.</p>';results.querySelectorAll("[data-school-result]").forEach(x=>x.addEventListener("click",()=>{const s=rows[Number(x.dataset.schoolResult)],p=$("#profileForm");p.elements.school_name.value=s.name||"";p.elements.school_type.value=s.school_type||"";p.elements.school_address.value=s.address||"";p.elements.school_zip.value=s.zip||"";p.elements.school_city.value=s.city||"";p.elements.school_phone.value=s.phone||"";p.elements.federal_state.value=v.state;p.elements.external_school_id.value=s.id||"";p.elements.school_source.value="jedeschule";results.innerHTML=`<p class="school-selected">✓ ${esc(s.name)} übernommen. Jetzt Schulprofil speichern.</p>`;p.scrollIntoView({behavior:"smooth",block:"center"})}))}catch(err){results.innerHTML='<p class="organizer-empty">Die Schulsuche ist gerade nicht erreichbar. Die Schule kann darunter selbst eingetragen werden.</p>'}finally{b.disabled=false}})}
function cleanEmpty(v){return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,x===""?null:x]))}
async function loadHoliday(){const card=$("#holidayCard"),code=snapshot?.profile?.federal_state;if(!code){card.querySelector("b").textContent="Bundesland im Schulprofil auswählen";return}const now=new Date(),to=new Date(now);to.setFullYear(to.getFullYear()+1);const iso=d=>d.toISOString().slice(0,10);try{const url=`https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE&subdivisionCode=${code}&validFrom=${iso(now)}&validTo=${iso(to)}&languageIsoCode=DE`;const rows=await fetch(url).then(r=>{if(!r.ok)throw new Error();return r.json()});const next=rows.filter(x=>new Date(x.endDate)>=now).sort((a,b)=>new Date(a.startDate)-new Date(b.startDate))[0];if(!next)throw new Error();const name=next.name?.find(x=>x.language==="DE")?.text||next.name?.[0]?.text||"Ferien";const days=Math.max(0,Math.ceil((new Date(next.startDate)-now)/86400000));card.querySelector("b").textContent=`${name} · ${days===0?"jetzt":`in ${days} Tagen`}`;card.querySelector("p").textContent=`${fmt(next.startDate)} bis ${fmt(next.endDate)} · ${states[code]}`;}catch(e){card.querySelector("b").textContent=`Ferien für ${states[code]||code}`;card.querySelector("p").textContent="Ferientermine konnten gerade nicht geladen werden."}}
window.BuhrsiOrganizer={openChooser,home:openHome,async open(tab="overview"){setTab(tab);await openSchool()}};
