const rewardsRoot=document.getElementById("rewardsSection");
const rewardCatalog={
 vbucks:{name:"V-Bucks",brand:"FORTNITE",seal:"V",className:"voucher-vbucks"},
 robux:{name:"Robux",brand:"ROBLOX",seal:"R$",className:"voucher-robux"},
 brawl_pass:{name:"Brawl Pass",brand:"BRAWL STARS",seal:"★",className:"voucher-brawl"}
};
const rewardEsc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const rewardName=type=>rewardCatalog[type]?.name||"Gaming-Gutschein";
let rewardSnapshot=null,rewardLoading=false;

function rewardToast(text){const toast=document.getElementById("toast");if(!toast)return;toast.textContent=text;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2600)}
function voucherMarkup(type,data,disabled){const item=rewardCatalog[type];return `<button type="button" class="voucher ${item.className}" data-reward-type="${type}" ${disabled?"disabled":""}><span class="voucher-brand">${item.brand}</span><span class="voucher-title">${item.name}</span><span class="voucher-seal">${item.seal}</span><span class="voucher-cost">🎟 ${Number(data.goal).toLocaleString("de-DE")} XP · AUSWÄHLEN</span></button>`}
function sourceMarkup(label,icon,value){return `<div class="xp-source"><span>${icon} ${label}</span><b>${Number(value||0).toLocaleString("de-DE")} XP</b></div>`}
function historyMarkup(rows){if(!rows?.length)return "";return `<div class="reward-history">${rows.map(row=>`<div class="reward-history-row"><b>${rewardEsc(rewardName(row.reward_type))}</b><span class="${row.status}">${row.status==="approved"?"Eingelöst": "Abgelehnt"} · ${new Date(row.requested_at).toLocaleDateString("de-DE")}</span></div>`).join("")}</div>`}
function pendingMarkup(data){if(!data.pending)return "";const label=rewardName(data.pending.reward_type);return `<div class="voucher-requested"><b>⏳ ${rewardEsc(label)} wartet auf Freigabe</b><small>${Number(data.pending.xp_cost).toLocaleString("de-DE")} XP werden erst nach der Genehmigung abgezogen.</small>${data.is_parent?`<div class="reward-parent-actions"><button class="reward-reject" type="button" data-reward-resolve="reject">ABLEHNEN</button><button class="reward-approve" type="button" data-reward-resolve="approve">GENEHMIGEN</button></div>`:""}</div>`}
function rulesMarkup(){return `<details class="xp-rules"><summary>So sammelst du XP</summary><div class="xp-rules-grid"><div class="xp-rule"><span>10 / 20 / 30 Min. lernen</span><b>10 / 25 / 40 XP</b></div><div class="xp-rule"><span>45 / 60 Min. lernen</span><b>65 / 90 XP</b></div><div class="xp-rule"><span>Hausaufgaben erledigt</span><b>15 XP</b></div><div class="xp-rule"><span>Note 1 / Note 2</span><b>400 / 200 XP</b></div><div class="xp-rule"><span>Note 3 / Note 4</span><b>75 / 25 XP</b></div><div class="xp-rule"><span>Note 5 oder 6</span><b>0 XP</b></div></div></details>`}
function renderRewards(){if(!rewardsRoot||!rewardSnapshot)return;const data=rewardSnapshot,xp=Math.max(0,Number(data.xp)||0),goal=Number(data.goal)||2500,missing=Math.max(0,goal-xp),ready=xp>=goal&&!data.pending,sources=data.sources||{};rewardsRoot.innerHTML=`<div class="rewards-head"><div><span class="eyebrow">DEIN NÄCHSTES ZIEL</span><h2>Gaming-Belohnung</h2><p>${ready?"Du hast es geschafft – such dir deinen Gutschein aus!":data.pending?"Deine Auswahl wurde an deine Eltern geschickt.":"Sammle XP und entscheide selbst, was du möchtest."}</p></div><div class="reward-balance"><b>${xp.toLocaleString("de-DE")}</b><small>DEINE XP</small></div></div><div class="reward-progress"><i style="width:${Math.min(100,xp/goal*100)}%"></i></div><div class="reward-distance"><span><strong>${Math.min(xp,goal).toLocaleString("de-DE")}</strong> von ${goal.toLocaleString("de-DE")} XP</span><span>${missing?`Noch ${missing.toLocaleString("de-DE")} XP`:"Ziel erreicht ✓"}</span></div>${pendingMarkup(data)}<div class="voucher-grid">${Object.keys(rewardCatalog).map(type=>voucherMarkup(type,data,!ready||data.is_parent)).join("")}</div><h3 class="xp-source-title">Deine gesammelten XP</h3><div class="xp-sources">${sourceMarkup("Zähneputzen","🪥",sources.brushing)}${sourceMarkup("Lernen","📚",sources.learning)}${sourceMarkup("Hausaufgaben","📝",sources.homework)}${sourceMarkup("Noten","🏆",sources.grades)}</div>${rulesMarkup()}${historyMarkup(data.history)}</div>`;bindRewardActions()}
function bindRewardActions(){rewardsRoot.querySelectorAll("[data-reward-type]").forEach(button=>button.addEventListener("click",async()=>{const type=button.dataset.rewardType,label=rewardName(type);if(!confirm(`${label} für 2.500 XP bei deinen Eltern anfragen?`))return;button.disabled=true;try{await window.BuhrsiRewardsAPI.request(type);rewardToast(`${label} wurde angefragt.`);await loadRewards()}catch(error){rewardToast(error.message||"Anfrage konnte nicht gesendet werden.");button.disabled=false}}));rewardsRoot.querySelectorAll("[data-reward-resolve]").forEach(button=>button.addEventListener("click",async()=>{const approved=button.dataset.rewardResolve==="approve";button.disabled=true;try{await window.BuhrsiRewardsAPI.resolve(rewardSnapshot.pending.id,approved);rewardToast(approved?"Belohnung genehmigt und XP abgezogen.":"Belohnung abgelehnt. Die XP bleiben erhalten.");await loadRewards()}catch(error){rewardToast(error.message||"Anfrage konnte nicht bearbeitet werden.");button.disabled=false}}))}
async function loadRewards(){if(!rewardsRoot||rewardLoading||!window.BuhrsiRewardsAPI?.child?.())return;rewardLoading=true;try{rewardSnapshot=await window.BuhrsiRewardsAPI.snapshot();renderRewards()}catch(error){rewardsRoot.innerHTML=`<p class="rewards-empty">Belohnungen konnten nicht geladen werden.<br><small>${rewardEsc(error.message)}</small></p>`}finally{rewardLoading=false}}

window.addEventListener("buhrsi:child-change",()=>setTimeout(loadRewards,80));
window.addEventListener("buhrsi:progress-saved",()=>setTimeout(loadRewards,80));
document.getElementById("mainNav")?.addEventListener("click",event=>{if(event.target.closest('[data-nav-target="rewardsSection"]'))loadRewards()});
setTimeout(loadRewards,1200);
